### ISSUE TITLE
Menu responsive ne fonctionne pas

### ISSUE THREAD

**Issue by SimplonReunion** [zneel/gestion-materiel#8]
Les éléments du menu ne s'affichent pas sur mobile/tablet

**Comment by zneel** [comment]
fixed on https://github.com/zneel/gestion-materiel/commit/013272eb4e767f21a07109c5a9f8b66cf873dc3a

**Comment by AshvinPainiaye** [comment]
fixed on https://github.com/zneel/gestion-materiel/pull/14/commits/af30b16269735203405dcacab56ce014e5ae2445
